# Standalone Iceberg REST Server Configuration
# (Only used if Gravitino is started in standalone REST mode.
#  In auxiliary mode, all settings come from gravitino.conf.)

gravitino.iceberg-rest.host = 0.0.0.0
gravitino.iceberg-rest.httpPort = 9001
gravitino.iceberg-rest.catalog-backend = jdbc
gravitino.iceberg-rest.uri = jdbc:postgresql://iceberg-postgres:5432/iceberg
gravitino.iceberg-rest.jdbc-user = iceberg
gravitino.iceberg-rest.jdbc-password = password
gravitino.iceberg-rest.jdbc-driver = org.postgresql.Driver
gravitino.iceberg-rest.jdbc-initialize = true
gravitino.iceberg-rest.warehouse = s3a://warehouse
gravitino.iceberg-rest.catalog-backend-name = olake_iceberg
gravitino.iceberg-rest.io-impl = org.apache.iceberg.aws.s3.S3FileIO
gravitino.iceberg-rest.s3-endpoint = http://minio:9000
gravitino.iceberg-rest.s3-region = us-east-1
gravitino.iceberg-rest.s3-path-style-access = true
gravitino.iceberg-rest.s3-access-key-id = admin
gravitino.iceberg-rest.s3-secret-access-key = password
gravitino.iceberg-rest.credential-providers = s3-secret-key
